from email.message import EmailMessage
import smtplib
import random

#Email library initializations
server = smtplib.SMTP('smtp.gmail.com', 587)

server.starttls()

#For this app to work you need a gmail account with 2FA, and an App Password (16-character password generated by Google)
server.login("theEmailToSendNotificationsFrom@gmail.com", "your App Password, something like: abcd efgh ijkl mnop")


# USER DATA

# Dictionary: contains the names and emails of the participants as well as two binary digits
# The first digit indicates whether the participant has already received a gift or not
# The second digit indicates whether the participant has already sent a gift or not

# The dictionary's syntax goes as follows:
# name : [email, hasReceived, hasSent]
# 0 = false ; 1 = true

# Both digits should be initialized as 0  for all users, only the name and email need to be changed


dict = {
    "ARAGORN": ["exampleAragorn@gmail.com", 0, 0],
    "BILBO": ["exampleBilbo@icloud.com", 0, 0],
    "CELEBRIMBOR": ["exampleCelebrimbor@gmail.com", 0, 0],
    "DENETHOR": ["exampleDenethor@yahoo.com", 0, 0],
    "ELENDIL": ["exampleElendil@gmail.com", 0, 0],
    "FRODO": ["exampleFrodo@gmail.com", 0, 0],
    "GIL-GALAD": ["exampleGilGalad@gmail.com", 0, 0],
    "HÚRIN": ["exampleHurin@yahoo.com", 0, 0],
    "ISILDUR": ["exampleIsildur@me.com", 0, 0]
}

# List of participants who haven't received a gift yet, needs to match the names from the dictionary

toGift = ["ARAGORN", "BILBO", "CELEBRIMBOR", "DENETHOR", "ELENDIL", "FRODO", "GIL-GALAD", "HÚRIN", "ISILDUR"]

def getNameFromDict(email): # Gets the name of the email's owner
    for name, data in dict.items():
        if data[0] == email:
            return name

def sendEmail(emailRecipient, giftReceiver): # Email construction and sending
    msg = EmailMessage()
    msg['Subject'] = "Secret Santa!"
    msg['From'] = "theEmailToSendNotificationsFrom@gmail.com"
    msg['To'] = emailRecipient
    msg.set_content("¡Merry Christmas " + getNameFromDict(emailRecipient) + "! This year you get to gift " + giftReceiver + ".") #sets the content of the email message

    server.send_message(msg)# -- This line of code sends the emails to the recipients.
    print("Email sent!")


# Logic of the program:

for sender in dict.keys(): # Repeat for each person in the dictionary

    if dict[sender][1] == 0:  # sender has not received a gift yet, due to this, sender appears in the toGift list and will be removed from the current draw
        toGift.remove(sender) # in other words, it prevents the sender from gifting to itself

    if len(toGift) == 2: # prevents fatal error during the gift distribution that would cause someone to remain giftless in one specific scenario
        notFound = True
        i = 0
        while notFound:
            if dict[toGift[i]][1] == 0 & dict[toGift[i]][2] == 0:
                receiver = toGift[i]
                notFound = False
    else:
        receiver = random.choice(toGift)  # chooses someone at random to receive a gift from the list of people without gifts

    dict[receiver][1] = 1 # Records that the receiver has received a gift
    dict[sender][2] = 1 # Records that the sender has sent a gift

    sendEmail(dict[sender][0], receiver) # Calls the function responsible for sending the emails

    toGift.remove(receiver) # Removes the person who received the gift from the "toGift" list

    if (dict[sender][1] == 0):  # sender has not received a gift yet, thus will be reinserted for the next draw
        toGift.append(sender)

    print(sender + " " + dict[sender][0] + " " + receiver) # Print who gifted to whom - for testing/troubleshooting purposes only

# Check that everyone has both sent and received a gift
for p in dict.keys():
    if not (dict[p][1] == 1 & dict[p][2] == 1):
        print(p + " has either not sent or not received a gift!")
        raise ValueError('-- ERROR -- ')
